/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Clinic } from "./Clinic";
import { ClinicCountArgs } from "./ClinicCountArgs";
import { ClinicFindManyArgs } from "./ClinicFindManyArgs";
import { ClinicFindUniqueArgs } from "./ClinicFindUniqueArgs";
import { DeleteClinicArgs } from "./DeleteClinicArgs";
import { ClinicService } from "../clinic.service";
@graphql.Resolver(() => Clinic)
export class ClinicResolverBase {
  constructor(protected readonly service: ClinicService) {}

  async _clinicsMeta(
    @graphql.Args() args: ClinicCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Clinic])
  async clinics(@graphql.Args() args: ClinicFindManyArgs): Promise<Clinic[]> {
    return this.service.clinics(args);
  }

  @graphql.Query(() => Clinic, { nullable: true })
  async clinic(
    @graphql.Args() args: ClinicFindUniqueArgs
  ): Promise<Clinic | null> {
    const result = await this.service.clinic(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Clinic)
  async deleteClinic(
    @graphql.Args() args: DeleteClinicArgs
  ): Promise<Clinic | null> {
    try {
      return await this.service.deleteClinic(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
