/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClinicService } from "../clinic.service";
import { ClinicCreateInput } from "./ClinicCreateInput";
import { Clinic } from "./Clinic";
import { ClinicFindManyArgs } from "./ClinicFindManyArgs";
import { ClinicWhereUniqueInput } from "./ClinicWhereUniqueInput";
import { ClinicUpdateInput } from "./ClinicUpdateInput";

export class ClinicControllerBase {
  constructor(protected readonly service: ClinicService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Clinic })
  async createClinic(@common.Body() data: ClinicCreateInput): Promise<Clinic> {
    return await this.service.createClinic({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Clinic] })
  @ApiNestedQuery(ClinicFindManyArgs)
  async clinics(@common.Req() request: Request): Promise<Clinic[]> {
    const args = plainToClass(ClinicFindManyArgs, request.query);
    return this.service.clinics({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Clinic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async clinic(
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Clinic | null> {
    const result = await this.service.clinic({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Clinic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClinic(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() data: ClinicUpdateInput
  ): Promise<Clinic | null> {
    try {
      return await this.service.updateClinic({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Clinic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClinic(
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Clinic | null> {
    try {
      return await this.service.deleteClinic({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
